### ISSUE TITLE
Images start even lower than 100000

### ISSUE THREAD

**Issue by xpftw** [l1ving/ranet-clone#2]
If you 0 pad the jpg filenames you can start even lower:

from: [https://russianplanes.net/images/to1000/000001.jpg]( https://russianplanes.net/images/to1000/000001.jpg)
to: [https://russianplanes.net/images/to100000/099999.jpg](https://russianplanes.net/images/to100000/099999.jpg)

Should yield ~100,000 more images.

**Comment by 5HT2** [comment]
I didn't realize you had to zero-pad only the second half of the URLs, I tried without padding and with padding but for both. 

Will fix.

**Comment by xpftw** [comment]
Spot checked the upper limit too and found some more images above 301605.

E.g. [https://russianplanes.net/images/to302000/301670.jpg](https://russianplanes.net/images/to302000/301670.jpg)

It goes a bit higher than that (seemingly up to 301700) and there some images of trains and miscellaneous things interspersed here and there but there are aircraft.

Don't know exactly how high it goes but would probably want to iterate further URLs just to be sure.

**Comment by 5HT2** [comment]
to5000/004000.jpg seems to be the low end?

**Comment by 5HT2** [comment]
Nope, apparently to1000/000001.jpg exists

**Comment by 5HT2** [comment]
to302000/301691.jpg is as high as I can see

**Comment by xpftw** [comment]
> to302000/301691.jpg is as high as I can see

That's what I got as well.

**Comment by 5HT2** [comment]
Thank you for bringing this to my attention!

**Comment by xpftw** [comment]
No problem, happy to have helped!
